# Generated by Django 3.2.8 on 2021-11-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0002_auto_20211031_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='demo_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='source_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vote_ration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vote_total',
        ),
    ]
