# Generated by Django 3.2.8 on 2021-11-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0003_auto_20211119_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Planning stage', 'Planning stage 🗒️'), ('In development', 'In development ⚙️'), ('Up and running', 'Up and running 🌐')], default='Planning stage', max_length=160),
        ),
    ]
